# Shared file included by the makefiles used to build packages.
# This contains various information needed by the makefiles,
# and is autogenerated by configure to include various
# necessary details.

# Tools needed:

CC = gcc
STRIP = strip

# Package name and version number:

PROGRAM_PREFIX = ps
PACKAGE = psdoom
PACKAGE_NAME = psdoom
PACKAGE_STRING = psdoom 2012.02.05-1.6.0
PACKAGE_TARNAME = psdoom
PACKAGE_VERSION = 2012.02.05-1.6.0

# Documentation files to distribute with packages.

DOC_FILES = README       \
            COPYING      \
            ChangeLog    \
            NEWS         \
            NOT-BUGS     \
            CMDLINE      \
            TODO

