apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubedoom-chart.fullname" . }}
  labels:
    {{- include "kubedoom-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5900
      protocol: TCP
      name: vnc
  selector:
    {{- include "kubedoom-chart.selectorLabels" . | nindent 4 }}
