.TH chocolate\-server 6
.SH NAME
chocolate\-server \- dedicated server for chocolate\-doom
.SH SYNOPSIS
.B chocolate\-server
[OPTIONS]
.SH DESCRIPTION
.PP
Chocolate Doom is a modern doom engine designed to behave
as similar to the original doom game as is possible.
.PP
.B chocolate\-server
is a dedicated server for Chocolate Doom. It is equivalent to 
running 
.B chocolate\-doom
with the "-dedicated" option.
.PP
Game options are not specified to the server, which merely acts to
retransmit data between players in the game; parameters for the
game should be specified by the first player to connect to the server,
who is designated the controlling player.
.br
.SH OPTIONS
.TP
\fB-ignoreversion\fR
Ignore version mismatches between the server and the client. Using this
option may cause game desyncs to occur, or differences in protocol may
mean the netgame will simply not function at all. 
.TP
\fB-port <n>\fR
Use the specified UDP port for communications, instead of the default (2342). 
.TP
\fB-privateserver\fR
Don't register with the global master server.
.TP
\fB-servername <name>\fR
Specify a name for the server.
.SH SEE ALSO
\fBchocolate-doom\fR(6),
\fBchocolate-setup\fR(6)
.SH AUTHOR
Chocolate Doom is written and maintained by Simon Howard.
.PP
This manual was written by Jon Dowland.
.SH COPYRIGHT
Copyright \(co id Software Inc.
Copyright \(co 2005-8 Simon Howard.
.br
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

