.TH chocolate\-setup 6
.SH NAME
chocolate\-setup \- configuration tool for chocolate\-doom
.SH SYNOPSIS
.B chocolate\-setup
[OPTIONS]
.SH DESCRIPTION
.PP
Chocolate Doom is a modern Doom engine designed to behave
as similar to the original Doom game as is possible.
.PP
.B chocolate\-setup
is a tool for configuring Chocolate Doom. It provides a menu\-based
interface for the display, joystick, keyboard, mouse, sound and
compatibility settings.
.PP
.B chocolate\-setup
can also be used to start and join network games.
.PP
.SH OPTIONS
.TP
\fB-config <file>\fR
Load configuration from the specified file, instead of default.cfg. 
.TP
\fB-extraconfig <file>\fR
Load extra configuration from the specified file, instead of chocolate-doom.cfg. 
.SH SEE ALSO
\fBchocolate-doom\fR(6),
\fBdefault.cfg\fR(5),
\fBchocolate-doom.cfg\fR(5)
.SH AUTHOR
Chocolate Doom is written and maintained by Simon Howard.
.PP
This manual was written by Jon Dowland.
.SH COPYRIGHT
Copyright \(co id Software Inc.
Copyright \(co 2005-8 Simon Howard.
.br
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

